name: Metrics
on:
  # schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Medias
        if: ${{ success() || failure() }}
        uses: ZafkielEdt/metrics@master
        with:
          filename: medias.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: Daletkiel
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, watching, reading, characters
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 22
