name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Favorites anime and currently watching
        if: ${{ success() || failure() }}
        uses: FrancoGL/metrics@master
        with:
          filename: anilist.anime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: Daletkiel
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_limit: 4
      - name: Favorites manga and currenly reading
        if: ${{ success() || failure() }}
        uses: FrancoGL/metrics@master
        with:
          filename: anilist.manga.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_medias: manga
          plugin_anilist_sections: favorites, reading
          plugin_anilist_limit: 4
      - name: Favorites characters
        if: ${{ success() || failure() }}
        uses: FrancoGL/metrics@master
        with:
          filename: anilist.characters.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 22
